#!/bin/bash
#
# Lint a lot of stages files


function linting
{
# PHPCS Linting
  local PHP=$(which php)
  local phpFilesStaged=$(git diff --name-only --cached -- '*.php' '**/*.php')
  for file in $(echo "$phpFilesStaged" | tr " " "\n")
  do
    local linted=$("$PHP" vendor/bin/phpcs --warning-severity=4 --error-severity=1 --standard="$1" "$file")

    if [ "$linted" ]
    then
      echo -e "FAILURE on phpcs linting: "
      echo "$linted"
      exit 1
    fi
  done

  exit 0
}


case "${1}" in
    --about )
        echo "Lint with phpcs"
        ;;
    * )
        phpcsStandard="phpcs.xml"
        if [ -f "$phpcsStandard" ]; then
          linting "$phpcsStandard"
        fi
        ;;
esac
