#!/bin/bash

function midnight
{
	local currentHour=$(date +%H)
	if [ "$currentHour" > 0 ] && [ "$currentHour" < 7 ]
	then
		echo "Only commit during the day.\n\nGo to sleep!"
		exit 1
	fi
}

case "${1}" in
	--about )
		echo "Midnight committing not allowed"
		;;
	* )
		midnight
		;;
esac